name: ToimivaIssueClosed
on:
  issues:
    types:
      - closed
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on new issue
        uses: peter-evans/create-or-update-comment@v1 
        with:
          issue-number: ${{ github.event.issue.number }} 
          body: | 
           Issue is now closed. Well done dude!
